# Create configuration directories for SameBoy
mkdir -p /storage/emulated/0/RetroArch/config/SameBoy 2>/dev/null

# Download SameBoy core from the official buildbot and extract it to the root protected folder
curl -sL -o /data/data/com.retroarch.aarch64/cores/sameboy_temp.zip https://buildbot.libretro.com/nightly/android/latest/arm64-v8a/sameboy_libretro_android.so.zip
unzip -o /data/data/com.retroarch.aarch64/cores/sameboy_temp.zip -d /data/data/com.retroarch.aarch64/cores/ 2>/dev/null
chmod 755 /data/data/com.retroarch.aarch64/cores/sameboy_libretro_android.so 2>/dev/null
rm -f /data/data/com.retroarch.aarch64/cores/sameboy_temp.zip 2>/dev/null

# Inject SameBoy core options (Opting for the profile with "accurate" color correction)
echo -e 'sameboy_audio_interference = "0"\nsameboy_audio_interference_1 = "0"\nsameboy_audio_interference_2 = "0"\nsameboy_audio_output = "Game Boy #1"\nsameboy_auto_sgb_model = "Super Game Boy"\nsameboy_auto_sgb_model_1 = "Super Game Boy"\nsameboy_auto_sgb_model_2 = "Super Game Boy"\nsameboy_border = "Super Game Boy only"\nsameboy_color_correction_mode = "accurate"\nsameboy_color_correction_mode_1 = "emulate hardware"\nsameboy_color_correction_mode_2 = "emulate hardware"\nsameboy_high_pass_filter_mode = "accurate"\nsameboy_high_pass_filter_mode_1 = "accurate"\nsameboy_high_pass_filter_mode_2 = "accurate"\nsameboy_light_temperature = "0"\nsameboy_light_temperature_1 = "0"\nsameboy_light_temperature_2 = "0"\nsameboy_link = "enabled"\nsameboy_model = "Auto"\nsameboy_model_1 = "Auto"\nsameboy_model_2 = "Auto"\nsameboy_mono_palette = "greyscale"\nsameboy_mono_palette_1 = "greyscale"\nsameboy_mono_palette_2 = "greyscale"\nsameboy_rtc = "sync to system clock"\nsameboy_rumble = "rumble-enabled games"\nsameboy_rumble_1 = "rumble-enabled games"\nsameboy_rumble_2 = "rumble-enabled games"\nsameboy_screen_layout = "top-down"' > /storage/emulated/0/RetroArch/config/SameBoy/SameBoy.opt

# Inject SameBoy GameBoy Shader Preset (gb-pass setup)
echo -e 'shaders = "5"\nshader0 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/shader-files/gb-pass0.slang"\nalias0 = "PASS0"\nwrap_mode0 = "clamp_to_border"\nmipmap_input0 = "false"\nfilter_linear0 = "false"\nfloat_framebuffer0 = "false"\nsrgb_framebuffer0 = "false"\nscale_type_x0 = "viewport"\nscale_x0 = "1.000000"\nscale_type_y0 = "viewport"\nscale_y0 = "1.000000"\nshader1 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/shader-files/gb-pass1.slang"\nalias1 = "PASS1"\nwrap_mode1 = "clamp_to_border"\nmipmap_input1 = "false"\nfilter_linear1 = "false"\nfloat_framebuffer1 = "false"\nsrgb_framebuffer1 = "false"\nscale_type_x1 = "source"\nscale_x1 = "1.000000"\nscale_type_y1 = "source"\nscale_y1 = "1.000000"\nshader2 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/shader-files/gb-pass2.slang"\nalias2 = "PASS2"\nwrap_mode2 = "clamp_to_border"\nmipmap_input2 = "false"\nfilter_linear2 = "false"\nfloat_framebuffer2 = "false"\nsrgb_framebuffer2 = "false"\nscale_type_x2 = "source"\nscale_x2 = "1.000000"\nscale_type_y2 = "source"\nscale_y2 = "1.000000"\nshader3 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/shader-files/gb-pass3.slang"\nalias3 = "PASS3"\nwrap_mode3 = "clamp_to_border"\nmipmap_input3 = "false"\nfilter_linear3 = "false"\nfloat_framebuffer3 = "false"\nsrgb_framebuffer3 = "false"\nscale_type_x3 = "source"\nscale_x3 = "1.000000"\nscale_type_y3 = "source"\nscale_y3 = "1.000000"\nshader4 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/shader-files/gb-pass4.slang"\nalias4 = "PASS4"\nwrap_mode4 = "clamp_to_border"\nmipmap_input4 = "false"\nfilter_linear4 = "false"\nfloat_framebuffer4 = "false"\nsrgb_framebuffer4 = "false"\nscale_type_x4 = "source"\nscale_x4 = "1.000000"\nscale_type_y4 = "source"\nscale_y4 = "1.000000"\npalette = "5.000000"\nbrightness_mode = "1.000000"\nresponse_time = "0.330000"\ntextures = "COLOR_PALETTE;BACKGROUND"\nCOLOR_PALETTE = "/data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/resources/palette.png"\nCOLOR_PALETTE_mipmap = "false"\nCOLOR_PALETTE_linear = "false"\nCOLOR_PALETTE_wrap_mode = "clamp_to_border"\nBACKGROUND = "/data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/gameboy/resources/background.png"\nBACKGROUND_mipmap = "false"\nBACKGROUND_linear = "true"\nBACKGROUND_wrap_mode = "clamp_to_border"' > /storage/emulated/0/RetroArch/config/SameBoy/gb.slangp

# Inject LCD Grid Shader Preset (Useful as a secondary option for color games)
echo -e 'shaders = "2"\nshader0 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/lcd-cgwg/lcd-grid-v2.slang"\nalias0 = ""\nwrap_mode0 = "clamp_to_border"\nmipmap_input0 = "false"\nfilter_linear0 = "false"\nfloat_framebuffer0 = "false"\nsrgb_framebuffer0 = "false"\nscale_type_x0 = "viewport"\nscale_x0 = "1.000000"\nscale_type_y0 = "viewport"\nscale_y0 = "1.000000"\nshader1 = "../../../../../../data/user/0/com.retroarch.aarch64/shaders/shaders_slang/handheld/shaders/pixel_transparency/pixel_transparency.slang"\nalias1 = ""\nwrap_mode1 = "clamp_to_border"\nmipmap_input1 = "false"\nfilter_linear1 = "false"\nfloat_framebuffer1 = "false"\nsrgb_framebuffer1 = "false"\nscale_type_x1 = "viewport"\nscale_x1 = "1.000000"\nscale_type_y1 = "viewport"\nscale_y1 = "1.000000"\nRSUBPIX_R = "0.750000"\nGSUBPIX_G = "0.750000"\nBSUBPIX_B = "0.750000"\ngain = "1.500000"\ngamma = "2.200000"\nblacklevel = "0.000000"\nPT_PALETTE = "1.000000"\nPT_POLARIZER = "0.000000"\nPT_HIGHLIGHTS = "0.000000"' > /storage/emulated/0/RetroArch/config/SameBoy/SameBoy.slangp